# Generated by Django 2.0.4 on 2018-12-29 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('coat', 'coat'), ('jacket', 'jacket'), ('blazer', 'blazer'), ('vest', 'vest'), ('dress', 'dress'), ('jumpsuit', 'jumpsuit'), ('shirt/blouse', 'shirt/blouse'), ('t-shirt', 't-shirt'), ('tank top', 'tank top'), ('bodysuit', 'bodysuit'), ('sweatshirt', 'sweatshirt'), ('sweater', 'sweater'), ('cardigan', 'cardigan'), ('pants', 'pants'), ('jeans', 'jeans'), ('leggings', 'leggings'), ('shorts', 'shorts'), ('skirt', 'skirt'), ('shoes', 'shoes'), ('bag', 'bag'), ('accessory', 'accessory'), ('etc', 'etc')], max_length=163)),
                ('season', multiselectfield.db.fields.MultiSelectField(choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall'), ('winter', 'winter'), ('etc', 'etc')], max_length=29)),
                ('color', multiselectfield.db.fields.MultiSelectField(choices=[('black', 'black'), ('grey', 'grey'), ('white', 'white'), ('beige', 'beige'), ('brown', 'brown'), ('metallic', 'metallic'), ('purple', 'purple'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('orange', 'orange'), ('pink', 'pink'), ('off-white', 'off-white'), ('red', 'red'), ('neon', 'neon'), ('etc', 'etc')], max_length=97)),
                ('pattern', multiselectfield.db.fields.MultiSelectField(choices=[('animal print', 'animal print'), ('camouflage', 'camouflage'), ('floral', 'floral'), ('gingham', 'gingham'), ('plaid', 'plaid'), ('polka dot', 'polka dot'), ('solid', 'solid'), ('striped', 'striped')], max_length=68)),
                ('photoid', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='temp/', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='closet.Photo'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
